---
# System packages to install
system_packages:
  - git
  - curl
  - wget
  - vim
  - htop
  - net-tools
  - rsync
  - acl
  - python3
  - bat

  - build-essential
  - ufw
  - fail2ban
  - smartmontools
  - hdparm
  - bcache-tools
  - dislocker
  - open-vm-tools
  - r8168-dkms
  - nvidia-driver-575
  - nvidia-utils-575
  - nvidia-kernel-common-575
