---
# Storage Configuration

storage_settings:
  monitoring:
    email: "root"
    homehost: "<system>"

filesystems:
  - name: root
    source: "UUID=f9338bb6-76ea-4125-8931-1bb4cbc714b1"
    path: /
    fstype: ext4
    options: defaults

  - name: raid_array
    source: /dev/md0
    path: /mnt/external_hdd
    fstype: ext4
    options: defaults
    owner: root
    group: "{{ backup_gid }}"
    backup_owner: mrishab
    backup_group: mrishab
    raid:
      level: 5
      chunk_size: 512k
      algorithm: 2
      devices: [/dev/sda1, /dev/sdb1, /dev/sdd1]
    backups: ["/restore"]

  - name: wd_3tb
    source: "UUID=8b5fd151-41c4-441b-8f51-250e7c94a89e"
    path: /mnt/wd_portable_hdd_3tb
    fstype: ext4
    options: "defaults,nofail"
    owner: root
    group: root

  - name: sony_1tb
    source: "UUID=68b809bb-5242-4d2c-9537-e17f6b3b54aa"
    path: /mnt/sony_portable_hdd_1tb
    fstype: ext4
    options: "defaults,nofail"
    owner: root
    group: root

  - name: wd_1000
    path: /mnt/wd_1000
    backups: ["/backups/"]

  - name: swap
    source: /swapfile
    path: none
    fstype: swap
    options: sw
